# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

parameters:
  tags: [ 'latest', $(tag) ]

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        repository: 'gowebapp'
        tags: |
          $(tag)
          latest
    - ${{ each tag in parameter.tags }}:
      - task: ECRPushImage@1
        displayName: Push Latest tag
        inputs:
          awsCredentials: 'AWS-UAT-SERVICE-CONN'
          regionName: 'eu-south-1'
          imageSource: 'imagename'
          sourceImageName: 'gowebapp'
          pushTag: ${{ tag }}
          repositoryName: 'ur-u-ecr'