# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

parameters:
- name: dockerimage
  displayName: 'The name of the docker image'
  type: string
  default: 'gowebapp'

- name: tags
  type: object
  default:
  - latest
  - $(tag)

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        repository: ${{ parameters.dockerimage }}
        tags: |
          $(tag)
          latest
    - ${{ each tag in parameters.tags }}:
      - task: ECRPushImage@1
        displayName: Push tag  ${{ parameters.dockerimage }} :${{ tag }}
        inputs:
          awsCredentials: 'AWS-UAT-SERVICE-CONN'
          regionName: 'eu-south-1'
          imageSource: 'imagename'
          sourceImageName: ${{ parameter.dockerimage }}
          pushTag: ${{ tag }}
          repositoryName: 'ur-u-ecr'