# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  os: '$(variables["Agent.OS"])'

parameters:
- name: 'SERVICECONN'
  displayName: 'Select the service connection related to the env.'
  type: string
  default: 'AWS Uat'
  values:
    - 'AWS Uat'
    - 'AWS Prod'
- name: tags
  type: object
  default:
  - latest
  - $(tag)

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo $(os)
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/webapp/Dockerfile'
        repository: $(DOCKER_IMAGE)
        tags: |
          $(tag)
          latest
    - ${{ each tag in parameters.tags }}:
      - task: ECRPushImage@1
        displayName: Push tag $(DOCKER_IMAGE) :${{ tag }}
        inputs:
          awsCredentials: ${{ parameters.SERVICECONN}}
          regionName: 'eu-south-1'
          imageSource: 'imagename'
          sourceImageName: $(DOCKER_IMAGE)
          pushTag: ${{ tag }}
          repositoryName: 'ur-u-ecr'
    - task: AWSCLI@1
      inputs:
        awsCredentials: ${{ parameters.SERVICECONN}}
        regionName: 'eu-south-1'
        awsCommand: 'ecs'
        awsSubCommand: 'update-service'
        awsArguments: '--cluster ur-u-ecs-cluster --service ur-u-ecs-service --force-new-deployment'